// <auto-generated />
using CinemaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CinemaApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030183649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CinemaApp.Models.Ator", b =>
                {
                    b.Property<int>("AtorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtorId"));

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AtorId");

                    b.ToTable("Atores");

                    b.HasData(
                        new
                        {
                            AtorId = 1,
                            Nacionalidade = "Americano",
                            Nome = "Tom Hanks"
                        },
                        new
                        {
                            AtorId = 2,
                            Nacionalidade = "Americana",
                            Nome = "Meryl Streep"
                        },
                        new
                        {
                            AtorId = 3,
                            Nacionalidade = "Americano",
                            Nome = "Leonardo DiCaprio"
                        },
                        new
                        {
                            AtorId = 4,
                            Nacionalidade = "Brasileira",
                            Nome = "Fernanda Montenegro"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            CategoriaId = 1,
                            Descricao = "Filmes de ação e aventura",
                            Nome = "Ação"
                        },
                        new
                        {
                            CategoriaId = 2,
                            Descricao = "Filmes dramáticos",
                            Nome = "Drama"
                        },
                        new
                        {
                            CategoriaId = 3,
                            Descricao = "Filmes cômicos",
                            Nome = "Comédia"
                        },
                        new
                        {
                            CategoriaId = 4,
                            Descricao = "Filmes de ficção científica",
                            Nome = "Ficção Científica"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Filme", b =>
                {
                    b.Property<int>("FilmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FilmeId"));

                    b.Property<int>("AnoLancamento")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoraId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmeId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ProdutoraId");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            FilmeId = 1,
                            AnoLancamento = 1994,
                            CategoriaId = 2,
                            ProdutoraId = 1,
                            Titulo = "Forrest Gump"
                        },
                        new
                        {
                            FilmeId = 2,
                            AnoLancamento = 1999,
                            CategoriaId = 1,
                            ProdutoraId = 1,
                            Titulo = "Matrix"
                        },
                        new
                        {
                            FilmeId = 3,
                            AnoLancamento = 1997,
                            CategoriaId = 2,
                            ProdutoraId = 2,
                            Titulo = "Titanic"
                        },
                        new
                        {
                            FilmeId = 4,
                            AnoLancamento = 1972,
                            CategoriaId = 2,
                            ProdutoraId = 3,
                            Titulo = "O Poderoso Chefão"
                        },
                        new
                        {
                            FilmeId = 5,
                            AnoLancamento = 1998,
                            CategoriaId = 2,
                            ProdutoraId = 4,
                            Titulo = "Central do Brasil"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.FilmeAtor", b =>
                {
                    b.Property<int>("FilmeId")
                        .HasColumnType("int");

                    b.Property<int>("AtorId")
                        .HasColumnType("int");

                    b.Property<string>("Personagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilmeId", "AtorId");

                    b.HasIndex("AtorId");

                    b.ToTable("FilmesAtores");

                    b.HasData(
                        new
                        {
                            FilmeId = 1,
                            AtorId = 1,
                            Personagem = "Forrest Gump"
                        },
                        new
                        {
                            FilmeId = 2,
                            AtorId = 1,
                            Personagem = "Personagem em Matrix"
                        },
                        new
                        {
                            FilmeId = 3,
                            AtorId = 3,
                            Personagem = "Jack Dawson"
                        },
                        new
                        {
                            FilmeId = 5,
                            AtorId = 4,
                            Personagem = "Dora"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Produtora", b =>
                {
                    b.Property<int>("ProdutoraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoraId"));

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaisOrigem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProdutoraId");

                    b.ToTable("Produtoras");

                    b.HasData(
                        new
                        {
                            ProdutoraId = 1,
                            Nome = "Warner Bros",
                            PaisOrigem = "EUA"
                        },
                        new
                        {
                            ProdutoraId = 2,
                            Nome = "Universal Pictures",
                            PaisOrigem = "EUA"
                        },
                        new
                        {
                            ProdutoraId = 3,
                            Nome = "Paramount",
                            PaisOrigem = "EUA"
                        },
                        new
                        {
                            ProdutoraId = 4,
                            Nome = "Globo Filmes",
                            PaisOrigem = "Brasil"
                        });
                });

            modelBuilder.Entity("CinemaApp.Models.Filme", b =>
                {
                    b.HasOne("CinemaApp.Models.Categoria", "Categoria")
                        .WithMany("Filmes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Models.Produtora", "Produtora")
                        .WithMany("Filmes")
                        .HasForeignKey("ProdutoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Produtora");
                });

            modelBuilder.Entity("CinemaApp.Models.FilmeAtor", b =>
                {
                    b.HasOne("CinemaApp.Models.Ator", "Ator")
                        .WithMany("FilmesAtores")
                        .HasForeignKey("AtorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CinemaApp.Models.Filme", "Filme")
                        .WithMany("FilmesAtores")
                        .HasForeignKey("FilmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ator");

                    b.Navigation("Filme");
                });

            modelBuilder.Entity("CinemaApp.Models.Ator", b =>
                {
                    b.Navigation("FilmesAtores");
                });

            modelBuilder.Entity("CinemaApp.Models.Categoria", b =>
                {
                    b.Navigation("Filmes");
                });

            modelBuilder.Entity("CinemaApp.Models.Filme", b =>
                {
                    b.Navigation("FilmesAtores");
                });

            modelBuilder.Entity("CinemaApp.Models.Produtora", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
